metrics<-read.table(file = "Desktop/Cartwright_Lab_Stuff/metrics_file.txt",header=TRUE)
metrics2<-read.table(file = "Desktop/Cartwright_Lab_Stuff/metrics_file2.txt", header=TRUE)
minia_sites <- c(metrics$var_sites)
velvet_sites <- c(metrics2$var_sites)
missing <- c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
g_range <- range(0, minia_sites, velvet_sites)
plot(missing, minia_sites, type="o", col="blue", ylim=g_range, axes=FALSE, ann=FALSE)
axis(1, at=0:9, lab=c("0","1","2","3","4","5","6","7","8","9"))
axis(2, las=1)
box()
lines(missing, velvet_sites, type="o", pch=22, col="red")
title(main="Sites vs. Missing", col.main="black")
title(xlab="Missing", col.lab=rgb(0,0.5,0))
title(ylab="Sites", col.lab=rgb(0,0.5,0))
legend(1, g_range[2], c("minia_sites","velvet_sites"), cex=0.8, col=c("blue","red"), pch=21:22, lty=1:2)
